alg: seq2seq
base_dir: log/seq2seq/random_search/taiwan/6
data:
  batch_size: 200
  dataset: data/npz/random_search/taiwan/6.npz
  test_batch_size: 1
  test_size: 0.27
  valid_size: 0.13
gpu: 0
input_features: '[''PM2.5'', ''DAY'', ''HOUR'', ''AMB_TEMP'', ''CO'', ''NO'', ''O3'',
  ''RH'', ''SO2'', ''WD_HR'', ''WS_HR'']'
log_level: INFO
model:
  horizon: 1
  input_dim: 11
  l1_decay: 0
  output_dim: 1
  rnn_layers: 1
  rnn_units: 100
  seq_len: 48
  type: bilstm_ed
  verified_percentage: 1
test:
  run_times: 1
  test_monthly: true
train:
  dropout: 0
  epochs: 300
  optimizer: adam
  patience: 30
